kịch bản video hướng dẫn từng bước — trình bày dạng video tutorial có thoại, từng bước rõ ràng, kết hợp phần hình ảnh minh họa , với nội dung sau: 
2-7-
Creating families
- [Instructor] We have now learned how to make changes to the Revit model, so let's have a look at creating elements from scratch starting with placing a point based family. I've currently got the Revit exercise file open for this video. This exercise will be placing a single furniture desk family as shown here in the top left, to do that we are going to filter all FamilySymbols or types in the document and find this one by matching the name 1,525 by 762 milliliters, so let's jump in to Visual Studio and get started. I've currently got the Visual Studio project file open for this video and here I've gone ahead and created a place family class. Which is a new IExternalCommand called Place Family. We can use this to place a family. Before we get started with the command, let's take a look at how to create families by searching for new family instance which is the method used to create families in the Object Browser. You can see that this is an overloaded method and it provides many ways to create a family. Each used in specific circumstances and each taking different parameters. As we want to create a point based family, that is inserted by selecting a point, we need to use one that starts with XYZ for point this one should work well. It allows us to insert a new family with the parameters location as XYZ, symbol for family type and a structural type enumeration which is required when placing some families and helps distinguish between structural elements. You might notice that the methods are created from a couple different objects. The document, and the item factory base. The others here at the bottom are for batch creation through the application which we won't be using. The creation.document object is different from the Revit document that we have been using, however it does store access to it. If we go to the document class in DB, and then look at its create property. We can see this returns the creation.document object used to create families, so let's click on that and next to the name it shows that this document inherits from the item factory base. So it can retrieve this object to create families from the creation namespace. So let's jump back to our command class, and look for the FamilySymbol so we can place a new desk into the project. Let's start by getting the FamilySymbol, by creating a filtered element collector using the variable collector and filtering the document by using the doc parameter. As we will be retrieving elements, let's start with an Ilist of elements with the variable symbols and assign to this our collector and for the filters, let's use a new shortcut OfClass. This lets us filter for elements by their class as shown in the DB namespace, so we can filter for classes that derive from the element class, in our case the FamilySymbol class. To add that class as a parameter, we need to add it as a parameter in the typeof operator. This returns the type of the class, so let's add typeof and then this take a parameter, let's use FamilySymbol so this will return the type of class the FamilySymbol is. To speed things up let's filter for FamilySymbols that are just family types, not instances. So to do this let's add WhereElementIsElementType and to retrieve the elements, let's use the ToElements method. Next we need to find which of the retrieved elements is the family symbol of the desk we are looking for. To do that, let's loop through each one until we find one that matches the FamilySymbol name. So let's create a FamilySymbol variable name symbol and assign to it null. We will then assign the family we find to this variable, to do that let's use a foreach loop, looping over each element as ele in the symbols list of elements. Inside of the loop let's check if a name and category match the family type we're after. Using an if statement let's check if the element name is equal to 1,525 by 762 millimeters as a string. If this is true, let's assign the element to the symbol variable as a FamilySymbol using the as keyword, and then break the loop as we have found our element. Perfect, so we have now filtered the document for the FamilySymbol we want, let's go ahead and place the family, to do that I've gone ahead and created a try, accept statement wrapping a transaction named Place Family, this contains the start and commit methods as required. After the start method is where we can place the family. Before we place the family however, we need to ensure that it is active, we need to do this because Revit will deactivate FamilySymbols to conserve memory. So to activate it let's first check if it is active using an if statement, and we can do this by accessing the IsActive property from the FamilySymbol which returns a Boolean, and to check if it returns false let's add an exclamation mark before the Boolean to invert it. If this returns false, let's use the Activate method from the FamilySymbol object which will simply activate it with no parameters. Now with the FamilySymbol active let's place it. Let's access the document property from the document create property, then NewFamilyInstance, and if you recall the version we want is one that takes an XYZ, this is basically a point that we can create with three coordinates in space as three parameters, so let's add new XYZ at zero, zero, zero. And then for the second parameter we need the symbol, and the third was the structural type enumeration which can be found in DB.structure, in StructuralType and NonStructural, perfect. This will now create a family, I've already gone ahead and added this in to the add-in manifest so let's go head and debug the command, and then open up the Revit exercise file associated with this video, and then go ahead and run the new command Place Family. Perfect, there's our new desk at zero, zero, zero. Being able to automatically place families can be used if you want to place many point based families at once like a large array of columns for instance.