kịch bản video hướng dẫn từng bước — trình bày dạng video tutorial có thoại, từng bước rõ ràng, kết hợp phần hình ảnh minh họa , với nội dung sau: 
2-9-
Creating line-based elements
Selecting transcript lines in this section will navigate to timestamp in the video
- [Instructor] In an earlier video, we learned how to place a family using an insertion point or XYZ. In this video, let's have a look at a different way to place elements such as using lines by creating walls directly in a Revit command. In this file, I've gone ahead and created a PlaceLineElement class which is a new IExternalCommand. Before we start placing walls, let's have a look at how to create one. Switch over to the Object Browser and I'm currently browsing the Custom Component Set which references the RevitAPI and RevitAPIUI files. Within here, I'm going to search for wall and then select the wall class. Here you can see the wall has create methods directly in the wall class as constructors and there are a few different ways that we can create them. Let's use this one that takes four different parameters. This requires the document, a curve, an element ID as the level and a Boolean to determine if it's structural or not. This will create a wall using the curves we provide as the center line and the default wall type. We already know how to retrieve the document and level through the filtered element collector, so let's take a closer look at the curve class. To look at the different types of curves we can create, we need to look at the derived types of the class. First expand the Curve class and then Derived Types. This shows us a few different types of curves we can create. Let's use the line class to create a line curve by using the CreateBound method which takes two XYZ objects for the start and end. Let's also try the Arc class to create an arc using three XYZ objects, the first point, the last point and the midpoint. So, let's switch back to our command and give this a try. As you can see, I've already gone ahead and created a FilteredElementCollector to find the level with the name Ground Floor. This may look a little bit different from our last FilteredElementCollectors as I've applied the shortcuts directly to the FilteredElementCollector object and I've found the level with the name Ground Floor. One thing to keep in mind here is if the collector does not find the level, that is one that's named Ground Floor, it will cause an exception, so to be safe, you could wrap this in a try catch statement. Now that we have our level, let's start creating our curves. To do that, we'll need to create some XYZ objects to set them out. We'll be creating three walls and an arc wall at the end. So, let's create four points for the corners and a point for the top of the arc. We can create these in clockwise order from the bottom left which we'll then use to set up the curves. To do this, let's start by creating five different XYZ objects named p1, p2 and so on. Then let's change the XYZ parameters for each point starting with the bottom left, that is negative 10 for X, negative 10 for Y and zero. Then for point two, 10 for X, negative 10 for Y and zero for Z. For point three, 15 for X for the midpoint and zero, zero. For point four, let's use 10, 10 and zero. And point five, let's use negative 10, 10 and zero. Now we can use these to create the curves. We'll need to store these curves in a list, so let's create a list of curve objects named Curves. Then let's create each of the curves starting with a line named l1. And to create the curve, let's access the CreateBound method from the line class. Then using p1 and p2 for the first line. For the arc, let's call it l2 and we need to access the create method from the arc class, then we need to provide the start point, end point and midpoint. So, let's use p1, p4 and then p3. Then let's create another line using p4 and p5 and we'll call that l3. Finally, one last curve called l4 and we'll use p5 and p1 to close the curves. And now for each of these curves, we need to append them to the curves list. We can do this using the add method. Great, so now let's use these and the WallCreate method to create the walls. To do that, we'll need to loop through each of the curves in the list and create a wall. We can do this inside of a transaction, so within the start and commit methods, let's use a foreach loop for each curve c in curves and for each one access the wall class .Create method providing the document, the curve, the level.Id and false for the structural type. Perfect. So, let's now try this command. I've already gone through the manifest and added this command in. So, go ahead and click Start to debug. And then open up the Revit exercise file for this video and try a new command in the Add-Ins tab and PlaceLineElement. Perfect, there's our walls. It looks like we have successfully created line-based elements automatically. One thing you may have noticed is we created the lines and arc outside of a transaction. This is because they don't need to be stored in the project and therefore don't need to be committed to the model. Revit is made up many line-based elements, so it's important to understand when to use different Revit Geometry types to create elements.